// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/reader.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Chunk         []byte                 `protobuf:"bytes,2,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_api_reader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_reader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_api_reader_proto_rawDescGZIP(), []int{0}
}

func (x *UploadRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *UploadRequest) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type Book struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_api_reader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_api_reader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_api_reader_proto_rawDescGZIP(), []int{1}
}

func (x *Book) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Book) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

type GetBooksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBooksRequest) Reset() {
	*x = GetBooksRequest{}
	mi := &file_api_reader_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBooksRequest) ProtoMessage() {}

func (x *GetBooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_reader_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBooksRequest.ProtoReflect.Descriptor instead.
func (*GetBooksRequest) Descriptor() ([]byte, []int) {
	return file_api_reader_proto_rawDescGZIP(), []int{2}
}

type GetBooksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Books         []*Book                `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBooksResponse) Reset() {
	*x = GetBooksResponse{}
	mi := &file_api_reader_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBooksResponse) ProtoMessage() {}

func (x *GetBooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_reader_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBooksResponse.ProtoReflect.Descriptor instead.
func (*GetBooksResponse) Descriptor() ([]byte, []int) {
	return file_api_reader_proto_rawDescGZIP(), []int{3}
}

func (x *GetBooksResponse) GetBooks() []*Book {
	if x != nil {
		return x.Books
	}
	return nil
}

type UploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_api_reader_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_reader_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_api_reader_proto_rawDescGZIP(), []int{4}
}

func (x *UploadResponse) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *UploadResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetPDFRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPDFRequest) Reset() {
	*x = GetPDFRequest{}
	mi := &file_api_reader_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPDFRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPDFRequest) ProtoMessage() {}

func (x *GetPDFRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_reader_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPDFRequest.ProtoReflect.Descriptor instead.
func (*GetPDFRequest) Descriptor() ([]byte, []int) {
	return file_api_reader_proto_rawDescGZIP(), []int{5}
}

func (x *GetPDFRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

type GetPDFChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPDFChunk) Reset() {
	*x = GetPDFChunk{}
	mi := &file_api_reader_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPDFChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPDFChunk) ProtoMessage() {}

func (x *GetPDFChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_reader_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPDFChunk.ProtoReflect.Descriptor instead.
func (*GetPDFChunk) Descriptor() ([]byte, []int) {
	return file_api_reader_proto_rawDescGZIP(), []int{6}
}

func (x *GetPDFChunk) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type Note struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BookId        string                 `protobuf:"bytes,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Note) Reset() {
	*x = Note{}
	mi := &file_api_reader_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Note) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Note) ProtoMessage() {}

func (x *Note) ProtoReflect() protoreflect.Message {
	mi := &file_api_reader_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Note.ProtoReflect.Descriptor instead.
func (*Note) Descriptor() ([]byte, []int) {
	return file_api_reader_proto_rawDescGZIP(), []int{7}
}

func (x *Note) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Note) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *Note) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Note) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type NoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	NoteId        string                 `protobuf:"bytes,2,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteResponse) Reset() {
	*x = NoteResponse{}
	mi := &file_api_reader_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteResponse) ProtoMessage() {}

func (x *NoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_reader_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteResponse.ProtoReflect.Descriptor instead.
func (*NoteResponse) Descriptor() ([]byte, []int) {
	return file_api_reader_proto_rawDescGZIP(), []int{8}
}

func (x *NoteResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *NoteResponse) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

type ListNotesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotesRequest) Reset() {
	*x = ListNotesRequest{}
	mi := &file_api_reader_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotesRequest) ProtoMessage() {}

func (x *ListNotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_reader_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotesRequest.ProtoReflect.Descriptor instead.
func (*ListNotesRequest) Descriptor() ([]byte, []int) {
	return file_api_reader_proto_rawDescGZIP(), []int{9}
}

func (x *ListNotesRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

type ReadingPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	CurrentPage   int32                  `protobuf:"varint,2,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadingPosition) Reset() {
	*x = ReadingPosition{}
	mi := &file_api_reader_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadingPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadingPosition) ProtoMessage() {}

func (x *ReadingPosition) ProtoReflect() protoreflect.Message {
	mi := &file_api_reader_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadingPosition.ProtoReflect.Descriptor instead.
func (*ReadingPosition) Descriptor() ([]byte, []int) {
	return file_api_reader_proto_rawDescGZIP(), []int{10}
}

func (x *ReadingPosition) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *ReadingPosition) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

type PositionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionResponse) Reset() {
	*x = PositionResponse{}
	mi := &file_api_reader_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionResponse) ProtoMessage() {}

func (x *PositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_reader_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionResponse.ProtoReflect.Descriptor instead.
func (*PositionResponse) Descriptor() ([]byte, []int) {
	return file_api_reader_proto_rawDescGZIP(), []int{11}
}

func (x *PositionResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_api_reader_proto protoreflect.FileDescriptor

const file_api_reader_proto_rawDesc = "" +
	"\n" +
	"\x10api/reader.proto\x12\x03api\">\n" +
	"\rUploadRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\x12\x14\n" +
	"\x05chunk\x18\x02 \x01(\fR\x05chunk\"D\n" +
	"\x04Book\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\"\x11\n" +
	"\x0fGetBooksRequest\"3\n" +
	"\x10GetBooksResponse\x12\x1f\n" +
	"\x05books\x18\x01 \x03(\v2\t.api.BookR\x05books\"9\n" +
	"\x0eUploadResponse\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\"(\n" +
	"\rGetPDFRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\"#\n" +
	"\vGetPDFChunk\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\"W\n" +
	"\x04Note\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\abook_id\x18\x02 \x01(\tR\x06bookId\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\"7\n" +
	"\fNoteResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x17\n" +
	"\anote_id\x18\x02 \x01(\tR\x06noteId\"+\n" +
	"\x10ListNotesRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\"M\n" +
	"\x0fReadingPosition\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\x12!\n" +
	"\fcurrent_page\x18\x02 \x01(\x05R\vcurrentPage\"\"\n" +
	"\x10PositionResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\x81\x03\n" +
	"\rReaderService\x124\n" +
	"\tUploadPDF\x12\x12.api.UploadRequest\x1a\x13.api.UploadResponse\x120\n" +
	"\x06GetPDF\x12\x12.api.GetPDFRequest\x1a\x10.api.GetPDFChunk0\x01\x12(\n" +
	"\bSaveNote\x12\t.api.Note\x1a\x11.api.NoteResponse\x12/\n" +
	"\tListNotes\x12\x15.api.ListNotesRequest\x1a\t.api.Note0\x01\x12;\n" +
	"\fSavePosition\x12\x14.api.ReadingPosition\x1a\x15.api.PositionResponse\x127\n" +
	"\vGetPosition\x12\x12.api.GetPDFRequest\x1a\x14.api.ReadingPosition\x127\n" +
	"\bGetBooks\x12\x14.api.GetBooksRequest\x1a\x15.api.GetBooksResponseB.Z,github.com/Paveluts42/bookreader/backend/apib\x06proto3"

var (
	file_api_reader_proto_rawDescOnce sync.Once
	file_api_reader_proto_rawDescData []byte
)

func file_api_reader_proto_rawDescGZIP() []byte {
	file_api_reader_proto_rawDescOnce.Do(func() {
		file_api_reader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_reader_proto_rawDesc), len(file_api_reader_proto_rawDesc)))
	})
	return file_api_reader_proto_rawDescData
}

var file_api_reader_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_reader_proto_goTypes = []any{
	(*UploadRequest)(nil),    // 0: api.UploadRequest
	(*Book)(nil),             // 1: api.Book
	(*GetBooksRequest)(nil),  // 2: api.GetBooksRequest
	(*GetBooksResponse)(nil), // 3: api.GetBooksResponse
	(*UploadResponse)(nil),   // 4: api.UploadResponse
	(*GetPDFRequest)(nil),    // 5: api.GetPDFRequest
	(*GetPDFChunk)(nil),      // 6: api.GetPDFChunk
	(*Note)(nil),             // 7: api.Note
	(*NoteResponse)(nil),     // 8: api.NoteResponse
	(*ListNotesRequest)(nil), // 9: api.ListNotesRequest
	(*ReadingPosition)(nil),  // 10: api.ReadingPosition
	(*PositionResponse)(nil), // 11: api.PositionResponse
}
var file_api_reader_proto_depIdxs = []int32{
	1,  // 0: api.GetBooksResponse.books:type_name -> api.Book
	0,  // 1: api.ReaderService.UploadPDF:input_type -> api.UploadRequest
	5,  // 2: api.ReaderService.GetPDF:input_type -> api.GetPDFRequest
	7,  // 3: api.ReaderService.SaveNote:input_type -> api.Note
	9,  // 4: api.ReaderService.ListNotes:input_type -> api.ListNotesRequest
	10, // 5: api.ReaderService.SavePosition:input_type -> api.ReadingPosition
	5,  // 6: api.ReaderService.GetPosition:input_type -> api.GetPDFRequest
	2,  // 7: api.ReaderService.GetBooks:input_type -> api.GetBooksRequest
	4,  // 8: api.ReaderService.UploadPDF:output_type -> api.UploadResponse
	6,  // 9: api.ReaderService.GetPDF:output_type -> api.GetPDFChunk
	8,  // 10: api.ReaderService.SaveNote:output_type -> api.NoteResponse
	7,  // 11: api.ReaderService.ListNotes:output_type -> api.Note
	11, // 12: api.ReaderService.SavePosition:output_type -> api.PositionResponse
	10, // 13: api.ReaderService.GetPosition:output_type -> api.ReadingPosition
	3,  // 14: api.ReaderService.GetBooks:output_type -> api.GetBooksResponse
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_api_reader_proto_init() }
func file_api_reader_proto_init() {
	if File_api_reader_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_reader_proto_rawDesc), len(file_api_reader_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_reader_proto_goTypes,
		DependencyIndexes: file_api_reader_proto_depIdxs,
		MessageInfos:      file_api_reader_proto_msgTypes,
	}.Build()
	File_api_reader_proto = out.File
	file_api_reader_proto_goTypes = nil
	file_api_reader_proto_depIdxs = nil
}
