// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: api/reader.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Chunk         []byte                 `protobuf:"bytes,2,opt,name=chunk,proto3" json:"chunk,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_api_reader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_reader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_api_reader_proto_rawDescGZIP(), []int{0}
}

func (x *UploadRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *UploadRequest) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *UploadRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UploadRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

type Book struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	FilePath      string                 `protobuf:"bytes,4,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,5,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	Page          int32                  `protobuf:"varint,6,opt,name=page,proto3" json:"page,omitempty"`
	PageAll       int32                  `protobuf:"varint,7,opt,name=pageAll,proto3" json:"pageAll,omitempty"`
	Notes         []*Note                `protobuf:"bytes,8,rep,name=notes,proto3" json:"notes,omitempty"` // List of notes associated with the book
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_api_reader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_api_reader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_api_reader_proto_rawDescGZIP(), []int{1}
}

func (x *Book) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Book) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Book) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *Book) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *Book) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Book) GetPageAll() int32 {
	if x != nil {
		return x.PageAll
	}
	return 0
}

func (x *Book) GetNotes() []*Note {
	if x != nil {
		return x.Notes
	}
	return nil
}

type GetBooksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBooksRequest) Reset() {
	*x = GetBooksRequest{}
	mi := &file_api_reader_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBooksRequest) ProtoMessage() {}

func (x *GetBooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_reader_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBooksRequest.ProtoReflect.Descriptor instead.
func (*GetBooksRequest) Descriptor() ([]byte, []int) {
	return file_api_reader_proto_rawDescGZIP(), []int{2}
}

type GetBooksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Books         []*Book                `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBooksResponse) Reset() {
	*x = GetBooksResponse{}
	mi := &file_api_reader_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBooksResponse) ProtoMessage() {}

func (x *GetBooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_reader_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBooksResponse.ProtoReflect.Descriptor instead.
func (*GetBooksResponse) Descriptor() ([]byte, []int) {
	return file_api_reader_proto_rawDescGZIP(), []int{3}
}

func (x *GetBooksResponse) GetBooks() []*Book {
	if x != nil {
		return x.Books
	}
	return nil
}

type UploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_api_reader_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_reader_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_api_reader_proto_rawDescGZIP(), []int{4}
}

func (x *UploadResponse) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *UploadResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type DeleteBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBookRequest) Reset() {
	*x = DeleteBookRequest{}
	mi := &file_api_reader_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookRequest) ProtoMessage() {}

func (x *DeleteBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_reader_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookRequest.ProtoReflect.Descriptor instead.
func (*DeleteBookRequest) Descriptor() ([]byte, []int) {
	return file_api_reader_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteBookRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

type DeleteBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBookResponse) Reset() {
	*x = DeleteBookResponse{}
	mi := &file_api_reader_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookResponse) ProtoMessage() {}

func (x *DeleteBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_reader_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookResponse.ProtoReflect.Descriptor instead.
func (*DeleteBookResponse) Descriptor() ([]byte, []int) {
	return file_api_reader_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteBookResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookRequest) Reset() {
	*x = GetBookRequest{}
	mi := &file_api_reader_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookRequest) ProtoMessage() {}

func (x *GetBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_reader_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookRequest.ProtoReflect.Descriptor instead.
func (*GetBookRequest) Descriptor() ([]byte, []int) {
	return file_api_reader_proto_rawDescGZIP(), []int{7}
}

func (x *GetBookRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

type GetBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Book          *Book                  `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // Error message if book not found
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookResponse) Reset() {
	*x = GetBookResponse{}
	mi := &file_api_reader_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookResponse) ProtoMessage() {}

func (x *GetBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_reader_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookResponse.ProtoReflect.Descriptor instead.
func (*GetBookResponse) Descriptor() ([]byte, []int) {
	return file_api_reader_proto_rawDescGZIP(), []int{8}
}

func (x *GetBookResponse) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

func (x *GetBookResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateBookPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBookPageRequest) Reset() {
	*x = UpdateBookPageRequest{}
	mi := &file_api_reader_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookPageRequest) ProtoMessage() {}

func (x *UpdateBookPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_reader_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookPageRequest.ProtoReflect.Descriptor instead.
func (*UpdateBookPageRequest) Descriptor() ([]byte, []int) {
	return file_api_reader_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateBookPageRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *UpdateBookPageRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type UpdateBookPageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBookPageResponse) Reset() {
	*x = UpdateBookPageResponse{}
	mi := &file_api_reader_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookPageResponse) ProtoMessage() {}

func (x *UpdateBookPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_reader_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookPageResponse.ProtoReflect.Descriptor instead.
func (*UpdateBookPageResponse) Descriptor() ([]byte, []int) {
	return file_api_reader_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateBookPageResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type Note struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BookId        string                 `protobuf:"bytes,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Note) Reset() {
	*x = Note{}
	mi := &file_api_reader_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Note) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Note) ProtoMessage() {}

func (x *Note) ProtoReflect() protoreflect.Message {
	mi := &file_api_reader_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Note.ProtoReflect.Descriptor instead.
func (*Note) Descriptor() ([]byte, []int) {
	return file_api_reader_proto_rawDescGZIP(), []int{11}
}

func (x *Note) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Note) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *Note) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Note) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type NoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	NoteId        string                 `protobuf:"bytes,2,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteResponse) Reset() {
	*x = NoteResponse{}
	mi := &file_api_reader_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteResponse) ProtoMessage() {}

func (x *NoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_reader_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteResponse.ProtoReflect.Descriptor instead.
func (*NoteResponse) Descriptor() ([]byte, []int) {
	return file_api_reader_proto_rawDescGZIP(), []int{12}
}

func (x *NoteResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *NoteResponse) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

type ListNotesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotesRequest) Reset() {
	*x = ListNotesRequest{}
	mi := &file_api_reader_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotesRequest) ProtoMessage() {}

func (x *ListNotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_reader_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotesRequest.ProtoReflect.Descriptor instead.
func (*ListNotesRequest) Descriptor() ([]byte, []int) {
	return file_api_reader_proto_rawDescGZIP(), []int{13}
}

func (x *ListNotesRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

type ReadingPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	CurrentPage   int32                  `protobuf:"varint,2,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadingPosition) Reset() {
	*x = ReadingPosition{}
	mi := &file_api_reader_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadingPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadingPosition) ProtoMessage() {}

func (x *ReadingPosition) ProtoReflect() protoreflect.Message {
	mi := &file_api_reader_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadingPosition.ProtoReflect.Descriptor instead.
func (*ReadingPosition) Descriptor() ([]byte, []int) {
	return file_api_reader_proto_rawDescGZIP(), []int{14}
}

func (x *ReadingPosition) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *ReadingPosition) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

type PositionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionResponse) Reset() {
	*x = PositionResponse{}
	mi := &file_api_reader_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionResponse) ProtoMessage() {}

func (x *PositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_reader_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionResponse.ProtoReflect.Descriptor instead.
func (*PositionResponse) Descriptor() ([]byte, []int) {
	return file_api_reader_proto_rawDescGZIP(), []int{15}
}

func (x *PositionResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetNotesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotesRequest) Reset() {
	*x = GetNotesRequest{}
	mi := &file_api_reader_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotesRequest) ProtoMessage() {}

func (x *GetNotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_reader_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotesRequest.ProtoReflect.Descriptor instead.
func (*GetNotesRequest) Descriptor() ([]byte, []int) {
	return file_api_reader_proto_rawDescGZIP(), []int{16}
}

func (x *GetNotesRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

type GetNotesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notes         []*Note                `protobuf:"bytes,1,rep,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotesResponse) Reset() {
	*x = GetNotesResponse{}
	mi := &file_api_reader_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotesResponse) ProtoMessage() {}

func (x *GetNotesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_reader_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotesResponse.ProtoReflect.Descriptor instead.
func (*GetNotesResponse) Descriptor() ([]byte, []int) {
	return file_api_reader_proto_rawDescGZIP(), []int{17}
}

func (x *GetNotesResponse) GetNotes() []*Note {
	if x != nil {
		return x.Notes
	}
	return nil
}

type AddNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNoteRequest) Reset() {
	*x = AddNoteRequest{}
	mi := &file_api_reader_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNoteRequest) ProtoMessage() {}

func (x *AddNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_reader_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNoteRequest.ProtoReflect.Descriptor instead.
func (*AddNoteRequest) Descriptor() ([]byte, []int) {
	return file_api_reader_proto_rawDescGZIP(), []int{18}
}

func (x *AddNoteRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *AddNoteRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AddNoteRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type AddNoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	NoteId        string                 `protobuf:"bytes,2,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"` // ID of the newly created note
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNoteResponse) Reset() {
	*x = AddNoteResponse{}
	mi := &file_api_reader_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNoteResponse) ProtoMessage() {}

func (x *AddNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_reader_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNoteResponse.ProtoReflect.Descriptor instead.
func (*AddNoteResponse) Descriptor() ([]byte, []int) {
	return file_api_reader_proto_rawDescGZIP(), []int{19}
}

func (x *AddNoteResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AddNoteResponse) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

var File_api_reader_proto protoreflect.FileDescriptor

const file_api_reader_proto_rawDesc = "" +
	"\n" +
	"\x10api/reader.proto\x12\x03api\"l\n" +
	"\rUploadRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\x12\x14\n" +
	"\x05chunk\x18\x02 \x01(\fR\x05chunk\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\"\xcd\x01\n" +
	"\x04Book\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x1b\n" +
	"\tfile_path\x18\x04 \x01(\tR\bfilePath\x12\x1b\n" +
	"\tcover_url\x18\x05 \x01(\tR\bcoverUrl\x12\x12\n" +
	"\x04page\x18\x06 \x01(\x05R\x04page\x12\x18\n" +
	"\apageAll\x18\a \x01(\x05R\apageAll\x12\x1f\n" +
	"\x05notes\x18\b \x03(\v2\t.api.NoteR\x05notes\"\x11\n" +
	"\x0fGetBooksRequest\"3\n" +
	"\x10GetBooksResponse\x12\x1f\n" +
	"\x05books\x18\x01 \x03(\v2\t.api.BookR\x05books\"9\n" +
	"\x0eUploadResponse\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\",\n" +
	"\x11DeleteBookRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\"$\n" +
	"\x12DeleteBookResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\")\n" +
	"\x0eGetBookRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\"F\n" +
	"\x0fGetBookResponse\x12\x1d\n" +
	"\x04book\x18\x01 \x01(\v2\t.api.BookR\x04book\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"D\n" +
	"\x15UpdateBookPageRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\"(\n" +
	"\x16UpdateBookPageResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"W\n" +
	"\x04Note\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\abook_id\x18\x02 \x01(\tR\x06bookId\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\"7\n" +
	"\fNoteResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x17\n" +
	"\anote_id\x18\x02 \x01(\tR\x06noteId\"+\n" +
	"\x10ListNotesRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\"M\n" +
	"\x0fReadingPosition\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\x12!\n" +
	"\fcurrent_page\x18\x02 \x01(\x05R\vcurrentPage\"\"\n" +
	"\x10PositionResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"*\n" +
	"\x0fGetNotesRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\"3\n" +
	"\x10GetNotesResponse\x12\x1f\n" +
	"\x05notes\x18\x01 \x03(\v2\t.api.NoteR\x05notes\"Q\n" +
	"\x0eaddNoteRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\":\n" +
	"\x0faddNoteResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x17\n" +
	"\anote_id\x18\x02 \x01(\tR\x06noteId2\xad\x03\n" +
	"\rReaderService\x124\n" +
	"\aAddNote\x12\x13.api.addNoteRequest\x1a\x14.api.addNoteResponse\x127\n" +
	"\bGetNotes\x12\x14.api.GetNotesRequest\x1a\x15.api.GetNotesResponse\x12=\n" +
	"\n" +
	"DeleteBook\x12\x16.api.DeleteBookRequest\x1a\x17.api.DeleteBookResponse\x124\n" +
	"\tUploadPDF\x12\x12.api.UploadRequest\x1a\x13.api.UploadResponse\x12I\n" +
	"\x0eUpdateBookPage\x12\x1a.api.UpdateBookPageRequest\x1a\x1b.api.UpdateBookPageResponse\x127\n" +
	"\bGetBooks\x12\x14.api.GetBooksRequest\x1a\x15.api.GetBooksResponse\x124\n" +
	"\aGetBook\x12\x13.api.GetBookRequest\x1a\x14.api.GetBookResponseB.Z,github.com/Paveluts42/bookreader/backend/apib\x06proto3"

var (
	file_api_reader_proto_rawDescOnce sync.Once
	file_api_reader_proto_rawDescData []byte
)

func file_api_reader_proto_rawDescGZIP() []byte {
	file_api_reader_proto_rawDescOnce.Do(func() {
		file_api_reader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_reader_proto_rawDesc), len(file_api_reader_proto_rawDesc)))
	})
	return file_api_reader_proto_rawDescData
}

var file_api_reader_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_api_reader_proto_goTypes = []any{
	(*UploadRequest)(nil),          // 0: api.UploadRequest
	(*Book)(nil),                   // 1: api.Book
	(*GetBooksRequest)(nil),        // 2: api.GetBooksRequest
	(*GetBooksResponse)(nil),       // 3: api.GetBooksResponse
	(*UploadResponse)(nil),         // 4: api.UploadResponse
	(*DeleteBookRequest)(nil),      // 5: api.DeleteBookRequest
	(*DeleteBookResponse)(nil),     // 6: api.DeleteBookResponse
	(*GetBookRequest)(nil),         // 7: api.GetBookRequest
	(*GetBookResponse)(nil),        // 8: api.GetBookResponse
	(*UpdateBookPageRequest)(nil),  // 9: api.UpdateBookPageRequest
	(*UpdateBookPageResponse)(nil), // 10: api.UpdateBookPageResponse
	(*Note)(nil),                   // 11: api.Note
	(*NoteResponse)(nil),           // 12: api.NoteResponse
	(*ListNotesRequest)(nil),       // 13: api.ListNotesRequest
	(*ReadingPosition)(nil),        // 14: api.ReadingPosition
	(*PositionResponse)(nil),       // 15: api.PositionResponse
	(*GetNotesRequest)(nil),        // 16: api.GetNotesRequest
	(*GetNotesResponse)(nil),       // 17: api.GetNotesResponse
	(*AddNoteRequest)(nil),         // 18: api.addNoteRequest
	(*AddNoteResponse)(nil),        // 19: api.addNoteResponse
}
var file_api_reader_proto_depIdxs = []int32{
	11, // 0: api.Book.notes:type_name -> api.Note
	1,  // 1: api.GetBooksResponse.books:type_name -> api.Book
	1,  // 2: api.GetBookResponse.book:type_name -> api.Book
	11, // 3: api.GetNotesResponse.notes:type_name -> api.Note
	18, // 4: api.ReaderService.AddNote:input_type -> api.addNoteRequest
	16, // 5: api.ReaderService.GetNotes:input_type -> api.GetNotesRequest
	5,  // 6: api.ReaderService.DeleteBook:input_type -> api.DeleteBookRequest
	0,  // 7: api.ReaderService.UploadPDF:input_type -> api.UploadRequest
	9,  // 8: api.ReaderService.UpdateBookPage:input_type -> api.UpdateBookPageRequest
	2,  // 9: api.ReaderService.GetBooks:input_type -> api.GetBooksRequest
	7,  // 10: api.ReaderService.GetBook:input_type -> api.GetBookRequest
	19, // 11: api.ReaderService.AddNote:output_type -> api.addNoteResponse
	17, // 12: api.ReaderService.GetNotes:output_type -> api.GetNotesResponse
	6,  // 13: api.ReaderService.DeleteBook:output_type -> api.DeleteBookResponse
	4,  // 14: api.ReaderService.UploadPDF:output_type -> api.UploadResponse
	10, // 15: api.ReaderService.UpdateBookPage:output_type -> api.UpdateBookPageResponse
	3,  // 16: api.ReaderService.GetBooks:output_type -> api.GetBooksResponse
	8,  // 17: api.ReaderService.GetBook:output_type -> api.GetBookResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_reader_proto_init() }
func file_api_reader_proto_init() {
	if File_api_reader_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_reader_proto_rawDesc), len(file_api_reader_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_reader_proto_goTypes,
		DependencyIndexes: file_api_reader_proto_depIdxs,
		MessageInfos:      file_api_reader_proto_msgTypes,
	}.Build()
	File_api_reader_proto = out.File
	file_api_reader_proto_goTypes = nil
	file_api_reader_proto_depIdxs = nil
}
