FROM golang:1.24-bookworm

WORKDIR /app

RUN apt-get update && apt-get install -y poppler-utils ffmpeg

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o backend ./cmd/server

RUN chown -R ${UID:-1000}:${GID:-1000} /app


EXPOSE 50051
CMD ["./backend"]