// @generated by protoc-gen-es v2.6.3 with parameter "target=ts"
// @generated from file book.proto (package api, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file book.proto.
 */
export const file_book: GenFile = /*@__PURE__*/
  fileDesc("Cgpib29rLnByb3RvEgNhcGkiiAEKBEJvb2sSCgoCaWQYASABKAkSDQoFdGl0bGUYAiABKAkSDgoGYXV0aG9yGAMgASgJEhEKCWZpbGVfcGF0aBgEIAEoCRIRCgljb3Zlcl91cmwYBSABKAkSDAoEcGFnZRgGIAEoBRIQCghwYWdlX2FsbBgHIAEoBRIPCgd1c2VyX2lkGAggASgJIl8KDVVwbG9hZFJlcXVlc3QSDwoHYm9va19pZBgBIAEoCRINCgVjaHVuaxgCIAEoDBINCgV0aXRsZRgDIAEoCRIOCgZhdXRob3IYBCABKAkSDwoHdXNlcl9pZBgFIAEoCSItCg5VcGxvYWRSZXNwb25zZRIPCgdib29rX2lkGAEgASgJEgoKAm9rGAIgASgIIiQKEURlbGV0ZUJvb2tSZXF1ZXN0Eg8KB2Jvb2tfaWQYASABKAkiIAoSRGVsZXRlQm9va1Jlc3BvbnNlEgoKAm9rGAEgASgIIhEKD0dldEJvb2tzUmVxdWVzdCIsChBHZXRCb29rc1Jlc3BvbnNlEhgKBWJvb2tzGAEgAygLMgkuYXBpLkJvb2siIQoOR2V0Qm9va1JlcXVlc3QSDwoHYm9va19pZBgBIAEoCSI5Cg9HZXRCb29rUmVzcG9uc2USFwoEYm9vaxgBIAEoCzIJLmFwaS5Cb29rEg0KBWVycm9yGAIgASgJIjYKFVVwZGF0ZUJvb2tQYWdlUmVxdWVzdBIPCgdib29rX2lkGAEgASgJEgwKBHBhZ2UYAiABKAUiJAoWVXBkYXRlQm9va1BhZ2VSZXNwb25zZRIKCgJvaxgBIAEoCDK8AgoLQm9va1NlcnZpY2USNAoJVXBsb2FkUERGEhIuYXBpLlVwbG9hZFJlcXVlc3QaEy5hcGkuVXBsb2FkUmVzcG9uc2USPQoKRGVsZXRlQm9vaxIWLmFwaS5EZWxldGVCb29rUmVxdWVzdBoXLmFwaS5EZWxldGVCb29rUmVzcG9uc2USNwoIR2V0Qm9va3MSFC5hcGkuR2V0Qm9va3NSZXF1ZXN0GhUuYXBpLkdldEJvb2tzUmVzcG9uc2USNAoHR2V0Qm9vaxITLmFwaS5HZXRCb29rUmVxdWVzdBoULmFwaS5HZXRCb29rUmVzcG9uc2USSQoOVXBkYXRlQm9va1BhZ2USGi5hcGkuVXBkYXRlQm9va1BhZ2VSZXF1ZXN0GhsuYXBpLlVwZGF0ZUJvb2tQYWdlUmVzcG9uc2VCLlosZ2l0aHViLmNvbS9QYXZlbHV0czQyL2Jvb2tyZWFkZXIvYmFja2VuZC9hcGliBnByb3RvMw");

/**
 * @generated from message api.Book
 */
export type Book = Message<"api.Book"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: string author = 3;
   */
  author: string;

  /**
   * @generated from field: string file_path = 4;
   */
  filePath: string;

  /**
   * @generated from field: string cover_url = 5;
   */
  coverUrl: string;

  /**
   * @generated from field: int32 page = 6;
   */
  page: number;

  /**
   * @generated from field: int32 page_all = 7;
   */
  pageAll: number;

  /**
   * @generated from field: string user_id = 8;
   */
  userId: string;
};

/**
 * Describes the message api.Book.
 * Use `create(BookSchema)` to create a new message.
 */
export const BookSchema: GenMessage<Book> = /*@__PURE__*/
  messageDesc(file_book, 0);

/**
 * @generated from message api.UploadRequest
 */
export type UploadRequest = Message<"api.UploadRequest"> & {
  /**
   * @generated from field: string book_id = 1;
   */
  bookId: string;

  /**
   * @generated from field: bytes chunk = 2;
   */
  chunk: Uint8Array;

  /**
   * @generated from field: string title = 3;
   */
  title: string;

  /**
   * @generated from field: string author = 4;
   */
  author: string;

  /**
   * @generated from field: string user_id = 5;
   */
  userId: string;
};

/**
 * Describes the message api.UploadRequest.
 * Use `create(UploadRequestSchema)` to create a new message.
 */
export const UploadRequestSchema: GenMessage<UploadRequest> = /*@__PURE__*/
  messageDesc(file_book, 1);

/**
 * @generated from message api.UploadResponse
 */
export type UploadResponse = Message<"api.UploadResponse"> & {
  /**
   * @generated from field: string book_id = 1;
   */
  bookId: string;

  /**
   * @generated from field: bool ok = 2;
   */
  ok: boolean;
};

/**
 * Describes the message api.UploadResponse.
 * Use `create(UploadResponseSchema)` to create a new message.
 */
export const UploadResponseSchema: GenMessage<UploadResponse> = /*@__PURE__*/
  messageDesc(file_book, 2);

/**
 * @generated from message api.DeleteBookRequest
 */
export type DeleteBookRequest = Message<"api.DeleteBookRequest"> & {
  /**
   * @generated from field: string book_id = 1;
   */
  bookId: string;
};

/**
 * Describes the message api.DeleteBookRequest.
 * Use `create(DeleteBookRequestSchema)` to create a new message.
 */
export const DeleteBookRequestSchema: GenMessage<DeleteBookRequest> = /*@__PURE__*/
  messageDesc(file_book, 3);

/**
 * @generated from message api.DeleteBookResponse
 */
export type DeleteBookResponse = Message<"api.DeleteBookResponse"> & {
  /**
   * @generated from field: bool ok = 1;
   */
  ok: boolean;
};

/**
 * Describes the message api.DeleteBookResponse.
 * Use `create(DeleteBookResponseSchema)` to create a new message.
 */
export const DeleteBookResponseSchema: GenMessage<DeleteBookResponse> = /*@__PURE__*/
  messageDesc(file_book, 4);

/**
 * @generated from message api.GetBooksRequest
 */
export type GetBooksRequest = Message<"api.GetBooksRequest"> & {
};

/**
 * Describes the message api.GetBooksRequest.
 * Use `create(GetBooksRequestSchema)` to create a new message.
 */
export const GetBooksRequestSchema: GenMessage<GetBooksRequest> = /*@__PURE__*/
  messageDesc(file_book, 5);

/**
 * @generated from message api.GetBooksResponse
 */
export type GetBooksResponse = Message<"api.GetBooksResponse"> & {
  /**
   * @generated from field: repeated api.Book books = 1;
   */
  books: Book[];
};

/**
 * Describes the message api.GetBooksResponse.
 * Use `create(GetBooksResponseSchema)` to create a new message.
 */
export const GetBooksResponseSchema: GenMessage<GetBooksResponse> = /*@__PURE__*/
  messageDesc(file_book, 6);

/**
 * @generated from message api.GetBookRequest
 */
export type GetBookRequest = Message<"api.GetBookRequest"> & {
  /**
   * @generated from field: string book_id = 1;
   */
  bookId: string;
};

/**
 * Describes the message api.GetBookRequest.
 * Use `create(GetBookRequestSchema)` to create a new message.
 */
export const GetBookRequestSchema: GenMessage<GetBookRequest> = /*@__PURE__*/
  messageDesc(file_book, 7);

/**
 * @generated from message api.GetBookResponse
 */
export type GetBookResponse = Message<"api.GetBookResponse"> & {
  /**
   * @generated from field: api.Book book = 1;
   */
  book?: Book;

  /**
   * @generated from field: string error = 2;
   */
  error: string;
};

/**
 * Describes the message api.GetBookResponse.
 * Use `create(GetBookResponseSchema)` to create a new message.
 */
export const GetBookResponseSchema: GenMessage<GetBookResponse> = /*@__PURE__*/
  messageDesc(file_book, 8);

/**
 * @generated from message api.UpdateBookPageRequest
 */
export type UpdateBookPageRequest = Message<"api.UpdateBookPageRequest"> & {
  /**
   * @generated from field: string book_id = 1;
   */
  bookId: string;

  /**
   * @generated from field: int32 page = 2;
   */
  page: number;
};

/**
 * Describes the message api.UpdateBookPageRequest.
 * Use `create(UpdateBookPageRequestSchema)` to create a new message.
 */
export const UpdateBookPageRequestSchema: GenMessage<UpdateBookPageRequest> = /*@__PURE__*/
  messageDesc(file_book, 9);

/**
 * @generated from message api.UpdateBookPageResponse
 */
export type UpdateBookPageResponse = Message<"api.UpdateBookPageResponse"> & {
  /**
   * @generated from field: bool ok = 1;
   */
  ok: boolean;
};

/**
 * Describes the message api.UpdateBookPageResponse.
 * Use `create(UpdateBookPageResponseSchema)` to create a new message.
 */
export const UpdateBookPageResponseSchema: GenMessage<UpdateBookPageResponse> = /*@__PURE__*/
  messageDesc(file_book, 10);

/**
 * @generated from service api.BookService
 */
export const BookService: GenService<{
  /**
   * @generated from rpc api.BookService.UploadPDF
   */
  uploadPDF: {
    methodKind: "unary";
    input: typeof UploadRequestSchema;
    output: typeof UploadResponseSchema;
  },
  /**
   * @generated from rpc api.BookService.DeleteBook
   */
  deleteBook: {
    methodKind: "unary";
    input: typeof DeleteBookRequestSchema;
    output: typeof DeleteBookResponseSchema;
  },
  /**
   * @generated from rpc api.BookService.GetBooks
   */
  getBooks: {
    methodKind: "unary";
    input: typeof GetBooksRequestSchema;
    output: typeof GetBooksResponseSchema;
  },
  /**
   * @generated from rpc api.BookService.GetBook
   */
  getBook: {
    methodKind: "unary";
    input: typeof GetBookRequestSchema;
    output: typeof GetBookResponseSchema;
  },
  /**
   * @generated from rpc api.BookService.UpdateBookPage
   */
  updateBookPage: {
    methodKind: "unary";
    input: typeof UpdateBookPageRequestSchema;
    output: typeof UpdateBookPageResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_book, 0);

