// @generated by protoc-gen-es v2.6.3 with parameter "target=ts"
// @generated from file note.proto (package api, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file note.proto.
 */
export const file_note: GenFile = /*@__PURE__*/
  fileDesc("Cgpub3RlLnByb3RvEgNhcGkiUAoETm90ZRIKCgJpZBgBIAEoCRIPCgdib29rX2lkGAIgASgJEgwKBHBhZ2UYAyABKAUSDAoEdGV4dBgEIAEoCRIPCgd1c2VyX2lkGAUgASgJIj0KDkFkZE5vdGVSZXF1ZXN0Eg8KB2Jvb2tfaWQYASABKAkSDAoEcGFnZRgCIAEoBRIMCgR0ZXh0GAMgASgJIi4KD0FkZE5vdGVSZXNwb25zZRIKCgJvaxgBIAEoCBIPCgdub3RlX2lkGAIgASgJIiIKD0dldE5vdGVzUmVxdWVzdBIPCgdib29rX2lkGAEgASgJIiwKEEdldE5vdGVzUmVzcG9uc2USGAoFbm90ZXMYASADKAsyCS5hcGkuTm90ZTJ8CgtOb3RlU2VydmljZRI0CgdBZGROb3RlEhMuYXBpLkFkZE5vdGVSZXF1ZXN0GhQuYXBpLkFkZE5vdGVSZXNwb25zZRI3CghHZXROb3RlcxIULmFwaS5HZXROb3Rlc1JlcXVlc3QaFS5hcGkuR2V0Tm90ZXNSZXNwb25zZUIuWixnaXRodWIuY29tL1BhdmVsdXRzNDIvYm9va3JlYWRlci9iYWNrZW5kL2FwaWIGcHJvdG8z");

/**
 * @generated from message api.Note
 */
export type Note = Message<"api.Note"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string book_id = 2;
   */
  bookId: string;

  /**
   * @generated from field: int32 page = 3;
   */
  page: number;

  /**
   * @generated from field: string text = 4;
   */
  text: string;

  /**
   * @generated from field: string user_id = 5;
   */
  userId: string;
};

/**
 * Describes the message api.Note.
 * Use `create(NoteSchema)` to create a new message.
 */
export const NoteSchema: GenMessage<Note> = /*@__PURE__*/
  messageDesc(file_note, 0);

/**
 * @generated from message api.AddNoteRequest
 */
export type AddNoteRequest = Message<"api.AddNoteRequest"> & {
  /**
   * @generated from field: string book_id = 1;
   */
  bookId: string;

  /**
   * @generated from field: int32 page = 2;
   */
  page: number;

  /**
   * @generated from field: string text = 3;
   */
  text: string;
};

/**
 * Describes the message api.AddNoteRequest.
 * Use `create(AddNoteRequestSchema)` to create a new message.
 */
export const AddNoteRequestSchema: GenMessage<AddNoteRequest> = /*@__PURE__*/
  messageDesc(file_note, 1);

/**
 * @generated from message api.AddNoteResponse
 */
export type AddNoteResponse = Message<"api.AddNoteResponse"> & {
  /**
   * @generated from field: bool ok = 1;
   */
  ok: boolean;

  /**
   * @generated from field: string note_id = 2;
   */
  noteId: string;
};

/**
 * Describes the message api.AddNoteResponse.
 * Use `create(AddNoteResponseSchema)` to create a new message.
 */
export const AddNoteResponseSchema: GenMessage<AddNoteResponse> = /*@__PURE__*/
  messageDesc(file_note, 2);

/**
 * @generated from message api.GetNotesRequest
 */
export type GetNotesRequest = Message<"api.GetNotesRequest"> & {
  /**
   * @generated from field: string book_id = 1;
   */
  bookId: string;
};

/**
 * Describes the message api.GetNotesRequest.
 * Use `create(GetNotesRequestSchema)` to create a new message.
 */
export const GetNotesRequestSchema: GenMessage<GetNotesRequest> = /*@__PURE__*/
  messageDesc(file_note, 3);

/**
 * @generated from message api.GetNotesResponse
 */
export type GetNotesResponse = Message<"api.GetNotesResponse"> & {
  /**
   * @generated from field: repeated api.Note notes = 1;
   */
  notes: Note[];
};

/**
 * Describes the message api.GetNotesResponse.
 * Use `create(GetNotesResponseSchema)` to create a new message.
 */
export const GetNotesResponseSchema: GenMessage<GetNotesResponse> = /*@__PURE__*/
  messageDesc(file_note, 4);

/**
 * @generated from service api.NoteService
 */
export const NoteService: GenService<{
  /**
   * @generated from rpc api.NoteService.AddNote
   */
  addNote: {
    methodKind: "unary";
    input: typeof AddNoteRequestSchema;
    output: typeof AddNoteResponseSchema;
  },
  /**
   * @generated from rpc api.NoteService.GetNotes
   */
  getNotes: {
    methodKind: "unary";
    input: typeof GetNotesRequestSchema;
    output: typeof GetNotesResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_note, 0);

