// @generated by protoc-gen-es v2.6.3 with parameter "target=ts"
// @generated from file reader.proto (package api, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file reader.proto.
 */
export const file_reader: GenFile = /*@__PURE__*/
  fileDesc("CgxyZWFkZXIucHJvdG8SA2FwaSIvCg1VcGxvYWRSZXF1ZXN0Eg8KB2Jvb2tfaWQYASABKAkSDQoFY2h1bmsYAiABKAwiMQoEQm9vaxIKCgJpZBgBIAEoCRINCgV0aXRsZRgCIAEoCRIOCgZhdXRob3IYAyABKAkiEQoPR2V0Qm9va3NSZXF1ZXN0IiwKEEdldEJvb2tzUmVzcG9uc2USGAoFYm9va3MYASADKAsyCS5hcGkuQm9vayItCg5VcGxvYWRSZXNwb25zZRIPCgdib29rX2lkGAEgASgJEgoKAm9rGAIgASgIIiAKDUdldFBERlJlcXVlc3QSDwoHYm9va19pZBgBIAEoCSIcCgtHZXRQREZDaHVuaxINCgVjaHVuaxgBIAEoDCI/CgROb3RlEgoKAmlkGAEgASgJEg8KB2Jvb2tfaWQYAiABKAkSDAoEcGFnZRgDIAEoBRIMCgR0ZXh0GAQgASgJIisKDE5vdGVSZXNwb25zZRIKCgJvaxgBIAEoCBIPCgdub3RlX2lkGAIgASgJIiMKEExpc3ROb3Rlc1JlcXVlc3QSDwoHYm9va19pZBgBIAEoCSI4Cg9SZWFkaW5nUG9zaXRpb24SDwoHYm9va19pZBgBIAEoCRIUCgxjdXJyZW50X3BhZ2UYAiABKAUiHgoQUG9zaXRpb25SZXNwb25zZRIKCgJvaxgBIAEoCDKBAwoNUmVhZGVyU2VydmljZRI0CglVcGxvYWRQREYSEi5hcGkuVXBsb2FkUmVxdWVzdBoTLmFwaS5VcGxvYWRSZXNwb25zZRIwCgZHZXRQREYSEi5hcGkuR2V0UERGUmVxdWVzdBoQLmFwaS5HZXRQREZDaHVuazABEigKCFNhdmVOb3RlEgkuYXBpLk5vdGUaES5hcGkuTm90ZVJlc3BvbnNlEi8KCUxpc3ROb3RlcxIVLmFwaS5MaXN0Tm90ZXNSZXF1ZXN0GgkuYXBpLk5vdGUwARI7CgxTYXZlUG9zaXRpb24SFC5hcGkuUmVhZGluZ1Bvc2l0aW9uGhUuYXBpLlBvc2l0aW9uUmVzcG9uc2USNwoLR2V0UG9zaXRpb24SEi5hcGkuR2V0UERGUmVxdWVzdBoULmFwaS5SZWFkaW5nUG9zaXRpb24SNwoIR2V0Qm9va3MSFC5hcGkuR2V0Qm9va3NSZXF1ZXN0GhUuYXBpLkdldEJvb2tzUmVzcG9uc2VCLlosZ2l0aHViLmNvbS9QYXZlbHV0czQyL2Jvb2tyZWFkZXIvYmFja2VuZC9hcGliBnByb3RvMw");

/**
 * @generated from message api.UploadRequest
 */
export type UploadRequest = Message<"api.UploadRequest"> & {
  /**
   * @generated from field: string book_id = 1;
   */
  bookId: string;

  /**
   * @generated from field: bytes chunk = 2;
   */
  chunk: Uint8Array;
};

/**
 * Describes the message api.UploadRequest.
 * Use `create(UploadRequestSchema)` to create a new message.
 */
export const UploadRequestSchema: GenMessage<UploadRequest> = /*@__PURE__*/
  messageDesc(file_reader, 0);

/**
 * @generated from message api.Book
 */
export type Book = Message<"api.Book"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: string author = 3;
   */
  author: string;
};

/**
 * Describes the message api.Book.
 * Use `create(BookSchema)` to create a new message.
 */
export const BookSchema: GenMessage<Book> = /*@__PURE__*/
  messageDesc(file_reader, 1);

/**
 * @generated from message api.GetBooksRequest
 */
export type GetBooksRequest = Message<"api.GetBooksRequest"> & {
};

/**
 * Describes the message api.GetBooksRequest.
 * Use `create(GetBooksRequestSchema)` to create a new message.
 */
export const GetBooksRequestSchema: GenMessage<GetBooksRequest> = /*@__PURE__*/
  messageDesc(file_reader, 2);

/**
 * @generated from message api.GetBooksResponse
 */
export type GetBooksResponse = Message<"api.GetBooksResponse"> & {
  /**
   * @generated from field: repeated api.Book books = 1;
   */
  books: Book[];
};

/**
 * Describes the message api.GetBooksResponse.
 * Use `create(GetBooksResponseSchema)` to create a new message.
 */
export const GetBooksResponseSchema: GenMessage<GetBooksResponse> = /*@__PURE__*/
  messageDesc(file_reader, 3);

/**
 * @generated from message api.UploadResponse
 */
export type UploadResponse = Message<"api.UploadResponse"> & {
  /**
   * @generated from field: string book_id = 1;
   */
  bookId: string;

  /**
   * @generated from field: bool ok = 2;
   */
  ok: boolean;
};

/**
 * Describes the message api.UploadResponse.
 * Use `create(UploadResponseSchema)` to create a new message.
 */
export const UploadResponseSchema: GenMessage<UploadResponse> = /*@__PURE__*/
  messageDesc(file_reader, 4);

/**
 * @generated from message api.GetPDFRequest
 */
export type GetPDFRequest = Message<"api.GetPDFRequest"> & {
  /**
   * @generated from field: string book_id = 1;
   */
  bookId: string;
};

/**
 * Describes the message api.GetPDFRequest.
 * Use `create(GetPDFRequestSchema)` to create a new message.
 */
export const GetPDFRequestSchema: GenMessage<GetPDFRequest> = /*@__PURE__*/
  messageDesc(file_reader, 5);

/**
 * @generated from message api.GetPDFChunk
 */
export type GetPDFChunk = Message<"api.GetPDFChunk"> & {
  /**
   * @generated from field: bytes chunk = 1;
   */
  chunk: Uint8Array;
};

/**
 * Describes the message api.GetPDFChunk.
 * Use `create(GetPDFChunkSchema)` to create a new message.
 */
export const GetPDFChunkSchema: GenMessage<GetPDFChunk> = /*@__PURE__*/
  messageDesc(file_reader, 6);

/**
 * @generated from message api.Note
 */
export type Note = Message<"api.Note"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string book_id = 2;
   */
  bookId: string;

  /**
   * @generated from field: int32 page = 3;
   */
  page: number;

  /**
   * @generated from field: string text = 4;
   */
  text: string;
};

/**
 * Describes the message api.Note.
 * Use `create(NoteSchema)` to create a new message.
 */
export const NoteSchema: GenMessage<Note> = /*@__PURE__*/
  messageDesc(file_reader, 7);

/**
 * @generated from message api.NoteResponse
 */
export type NoteResponse = Message<"api.NoteResponse"> & {
  /**
   * @generated from field: bool ok = 1;
   */
  ok: boolean;

  /**
   * @generated from field: string note_id = 2;
   */
  noteId: string;
};

/**
 * Describes the message api.NoteResponse.
 * Use `create(NoteResponseSchema)` to create a new message.
 */
export const NoteResponseSchema: GenMessage<NoteResponse> = /*@__PURE__*/
  messageDesc(file_reader, 8);

/**
 * @generated from message api.ListNotesRequest
 */
export type ListNotesRequest = Message<"api.ListNotesRequest"> & {
  /**
   * @generated from field: string book_id = 1;
   */
  bookId: string;
};

/**
 * Describes the message api.ListNotesRequest.
 * Use `create(ListNotesRequestSchema)` to create a new message.
 */
export const ListNotesRequestSchema: GenMessage<ListNotesRequest> = /*@__PURE__*/
  messageDesc(file_reader, 9);

/**
 * @generated from message api.ReadingPosition
 */
export type ReadingPosition = Message<"api.ReadingPosition"> & {
  /**
   * @generated from field: string book_id = 1;
   */
  bookId: string;

  /**
   * @generated from field: int32 current_page = 2;
   */
  currentPage: number;
};

/**
 * Describes the message api.ReadingPosition.
 * Use `create(ReadingPositionSchema)` to create a new message.
 */
export const ReadingPositionSchema: GenMessage<ReadingPosition> = /*@__PURE__*/
  messageDesc(file_reader, 10);

/**
 * @generated from message api.PositionResponse
 */
export type PositionResponse = Message<"api.PositionResponse"> & {
  /**
   * @generated from field: bool ok = 1;
   */
  ok: boolean;
};

/**
 * Describes the message api.PositionResponse.
 * Use `create(PositionResponseSchema)` to create a new message.
 */
export const PositionResponseSchema: GenMessage<PositionResponse> = /*@__PURE__*/
  messageDesc(file_reader, 11);

/**
 * @generated from service api.ReaderService
 */
export const ReaderService: GenService<{
  /**
   * @generated from rpc api.ReaderService.UploadPDF
   */
  uploadPDF: {
    methodKind: "unary";
    input: typeof UploadRequestSchema;
    output: typeof UploadResponseSchema;
  },
  /**
   * @generated from rpc api.ReaderService.GetPDF
   */
  getPDF: {
    methodKind: "server_streaming";
    input: typeof GetPDFRequestSchema;
    output: typeof GetPDFChunkSchema;
  },
  /**
   * @generated from rpc api.ReaderService.SaveNote
   */
  saveNote: {
    methodKind: "unary";
    input: typeof NoteSchema;
    output: typeof NoteResponseSchema;
  },
  /**
   * @generated from rpc api.ReaderService.ListNotes
   */
  listNotes: {
    methodKind: "server_streaming";
    input: typeof ListNotesRequestSchema;
    output: typeof NoteSchema;
  },
  /**
   * @generated from rpc api.ReaderService.SavePosition
   */
  savePosition: {
    methodKind: "unary";
    input: typeof ReadingPositionSchema;
    output: typeof PositionResponseSchema;
  },
  /**
   * @generated from rpc api.ReaderService.GetPosition
   */
  getPosition: {
    methodKind: "unary";
    input: typeof GetPDFRequestSchema;
    output: typeof ReadingPositionSchema;
  },
  /**
   * @generated from rpc api.ReaderService.GetBooks
   */
  getBooks: {
    methodKind: "unary";
    input: typeof GetBooksRequestSchema;
    output: typeof GetBooksResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_reader, 0);

