// @generated by protoc-gen-es v2.6.3 with parameter "target=ts"
// @generated from file user.proto (package api, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file user.proto.
 */
export const file_user: GenFile = /*@__PURE__*/
  fileDesc("Cgp1c2VyLnByb3RvEgNhcGkiNQoEVXNlchIKCgJpZBgBIAEoCRIQCgh1c2VybmFtZRgCIAEoCRIPCgdpc0FkbWluGAMgASgIIhEKD0dldFVzZXJzUmVxdWVzdCIsChBHZXRVc2Vyc1Jlc3BvbnNlEhgKBXVzZXJzGAEgAygLMgkuYXBpLlVzZXIiJAoRRGVsZXRlVXNlclJlcXVlc3QSDwoHdXNlcl9pZBgBIAEoCSIgChJEZWxldGVVc2VyUmVzcG9uc2USCgoCb2sYASABKAgiIQoOR2V0VXNlclJlcXVlc3QSDwoHdXNlcl9pZBgBIAEoCSJFCg9HZXRVc2VyUmVzcG9uc2USDwoHdXNlcl9pZBgBIAEoCRIQCgh1c2VybmFtZRgCIAEoCRIPCgdpc0FkbWluGAMgASgIIjUKD1JlZ2lzdGVyUmVxdWVzdBIQCgh1c2VybmFtZRgBIAEoCRIQCghwYXNzd29yZBgCIAEoCSI+ChBSZWdpc3RlclJlc3BvbnNlEg8KB3VzZXJfaWQYASABKAkSCgoCb2sYAiABKAgSDQoFZXJyb3IYAyABKAkiMgoMTG9naW5SZXF1ZXN0EhAKCHVzZXJuYW1lGAEgASgJEhAKCHBhc3N3b3JkGAIgASgJIosBCg1Mb2dpblJlc3BvbnNlEgoKAm9rGAEgASgIEg0KBWVycm9yGAIgASgJEhQKDGFjY2Vzc190b2tlbhgDIAEoCRIPCgd1c2VyX2lkGAQgASgJEhUKDXJlZnJlc2hfdG9rZW4YBSABKAkSEAoIdXNlcm5hbWUYBiABKAkSDwoHaXNBZG1pbhgHIAEoCCInCg5SZWZyZXNoUmVxdWVzdBIVCg1yZWZyZXNoX3Rva2VuGAEgASgJIk0KD1JlZnJlc2hSZXNwb25zZRIUCgxhY2Nlc3NfdG9rZW4YASABKAkSFQoNcmVmcmVzaF90b2tlbhgCIAEoCRINCgVlcnJvchgDIAEoCTLfAgoLVXNlclNlcnZpY2USNwoIR2V0VXNlcnMSFC5hcGkuR2V0VXNlcnNSZXF1ZXN0GhUuYXBpLkdldFVzZXJzUmVzcG9uc2USPQoKRGVsZXRlVXNlchIWLmFwaS5EZWxldGVVc2VyUmVxdWVzdBoXLmFwaS5EZWxldGVVc2VyUmVzcG9uc2USNAoHR2V0VXNlchITLmFwaS5HZXRVc2VyUmVxdWVzdBoULmFwaS5HZXRVc2VyUmVzcG9uc2USNwoIUmVnaXN0ZXISFC5hcGkuUmVnaXN0ZXJSZXF1ZXN0GhUuYXBpLlJlZ2lzdGVyUmVzcG9uc2USLgoFTG9naW4SES5hcGkuTG9naW5SZXF1ZXN0GhIuYXBpLkxvZ2luUmVzcG9uc2USOQoMUmVmcmVzaFRva2VuEhMuYXBpLlJlZnJlc2hSZXF1ZXN0GhQuYXBpLlJlZnJlc2hSZXNwb25zZUIuWixnaXRodWIuY29tL1BhdmVsdXRzNDIvYm9va3JlYWRlci9iYWNrZW5kL2FwaWIGcHJvdG8z");

/**
 * @generated from message api.User
 */
export type User = Message<"api.User"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string username = 2;
   */
  username: string;

  /**
   * @generated from field: bool isAdmin = 3;
   */
  isAdmin: boolean;
};

/**
 * Describes the message api.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_user, 0);

/**
 * @generated from message api.GetUsersRequest
 */
export type GetUsersRequest = Message<"api.GetUsersRequest"> & {
};

/**
 * Describes the message api.GetUsersRequest.
 * Use `create(GetUsersRequestSchema)` to create a new message.
 */
export const GetUsersRequestSchema: GenMessage<GetUsersRequest> = /*@__PURE__*/
  messageDesc(file_user, 1);

/**
 * @generated from message api.GetUsersResponse
 */
export type GetUsersResponse = Message<"api.GetUsersResponse"> & {
  /**
   * @generated from field: repeated api.User users = 1;
   */
  users: User[];
};

/**
 * Describes the message api.GetUsersResponse.
 * Use `create(GetUsersResponseSchema)` to create a new message.
 */
export const GetUsersResponseSchema: GenMessage<GetUsersResponse> = /*@__PURE__*/
  messageDesc(file_user, 2);

/**
 * @generated from message api.DeleteUserRequest
 */
export type DeleteUserRequest = Message<"api.DeleteUserRequest"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;
};

/**
 * Describes the message api.DeleteUserRequest.
 * Use `create(DeleteUserRequestSchema)` to create a new message.
 */
export const DeleteUserRequestSchema: GenMessage<DeleteUserRequest> = /*@__PURE__*/
  messageDesc(file_user, 3);

/**
 * @generated from message api.DeleteUserResponse
 */
export type DeleteUserResponse = Message<"api.DeleteUserResponse"> & {
  /**
   * @generated from field: bool ok = 1;
   */
  ok: boolean;
};

/**
 * Describes the message api.DeleteUserResponse.
 * Use `create(DeleteUserResponseSchema)` to create a new message.
 */
export const DeleteUserResponseSchema: GenMessage<DeleteUserResponse> = /*@__PURE__*/
  messageDesc(file_user, 4);

/**
 * @generated from message api.GetUserRequest
 */
export type GetUserRequest = Message<"api.GetUserRequest"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;
};

/**
 * Describes the message api.GetUserRequest.
 * Use `create(GetUserRequestSchema)` to create a new message.
 */
export const GetUserRequestSchema: GenMessage<GetUserRequest> = /*@__PURE__*/
  messageDesc(file_user, 5);

/**
 * @generated from message api.GetUserResponse
 */
export type GetUserResponse = Message<"api.GetUserResponse"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string username = 2;
   */
  username: string;

  /**
   * @generated from field: bool isAdmin = 3;
   */
  isAdmin: boolean;
};

/**
 * Describes the message api.GetUserResponse.
 * Use `create(GetUserResponseSchema)` to create a new message.
 */
export const GetUserResponseSchema: GenMessage<GetUserResponse> = /*@__PURE__*/
  messageDesc(file_user, 6);

/**
 * @generated from message api.RegisterRequest
 */
export type RegisterRequest = Message<"api.RegisterRequest"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message api.RegisterRequest.
 * Use `create(RegisterRequestSchema)` to create a new message.
 */
export const RegisterRequestSchema: GenMessage<RegisterRequest> = /*@__PURE__*/
  messageDesc(file_user, 7);

/**
 * @generated from message api.RegisterResponse
 */
export type RegisterResponse = Message<"api.RegisterResponse"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: bool ok = 2;
   */
  ok: boolean;

  /**
   * @generated from field: string error = 3;
   */
  error: string;
};

/**
 * Describes the message api.RegisterResponse.
 * Use `create(RegisterResponseSchema)` to create a new message.
 */
export const RegisterResponseSchema: GenMessage<RegisterResponse> = /*@__PURE__*/
  messageDesc(file_user, 8);

/**
 * @generated from message api.LoginRequest
 */
export type LoginRequest = Message<"api.LoginRequest"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message api.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export const LoginRequestSchema: GenMessage<LoginRequest> = /*@__PURE__*/
  messageDesc(file_user, 9);

/**
 * @generated from message api.LoginResponse
 */
export type LoginResponse = Message<"api.LoginResponse"> & {
  /**
   * @generated from field: bool ok = 1;
   */
  ok: boolean;

  /**
   * @generated from field: string error = 2;
   */
  error: string;

  /**
   * @generated from field: string access_token = 3;
   */
  accessToken: string;

  /**
   * @generated from field: string user_id = 4;
   */
  userId: string;

  /**
   * @generated from field: string refresh_token = 5;
   */
  refreshToken: string;

  /**
   * @generated from field: string username = 6;
   */
  username: string;

  /**
   * @generated from field: bool isAdmin = 7;
   */
  isAdmin: boolean;
};

/**
 * Describes the message api.LoginResponse.
 * Use `create(LoginResponseSchema)` to create a new message.
 */
export const LoginResponseSchema: GenMessage<LoginResponse> = /*@__PURE__*/
  messageDesc(file_user, 10);

/**
 * @generated from message api.RefreshRequest
 */
export type RefreshRequest = Message<"api.RefreshRequest"> & {
  /**
   * @generated from field: string refresh_token = 1;
   */
  refreshToken: string;
};

/**
 * Describes the message api.RefreshRequest.
 * Use `create(RefreshRequestSchema)` to create a new message.
 */
export const RefreshRequestSchema: GenMessage<RefreshRequest> = /*@__PURE__*/
  messageDesc(file_user, 11);

/**
 * @generated from message api.RefreshResponse
 */
export type RefreshResponse = Message<"api.RefreshResponse"> & {
  /**
   * @generated from field: string access_token = 1;
   */
  accessToken: string;

  /**
   * @generated from field: string refresh_token = 2;
   */
  refreshToken: string;

  /**
   * @generated from field: string error = 3;
   */
  error: string;
};

/**
 * Describes the message api.RefreshResponse.
 * Use `create(RefreshResponseSchema)` to create a new message.
 */
export const RefreshResponseSchema: GenMessage<RefreshResponse> = /*@__PURE__*/
  messageDesc(file_user, 12);

/**
 * @generated from service api.UserService
 */
export const UserService: GenService<{
  /**
   * @generated from rpc api.UserService.GetUsers
   */
  getUsers: {
    methodKind: "unary";
    input: typeof GetUsersRequestSchema;
    output: typeof GetUsersResponseSchema;
  },
  /**
   * @generated from rpc api.UserService.DeleteUser
   */
  deleteUser: {
    methodKind: "unary";
    input: typeof DeleteUserRequestSchema;
    output: typeof DeleteUserResponseSchema;
  },
  /**
   * @generated from rpc api.UserService.GetUser
   */
  getUser: {
    methodKind: "unary";
    input: typeof GetUserRequestSchema;
    output: typeof GetUserResponseSchema;
  },
  /**
   * @generated from rpc api.UserService.Register
   */
  register: {
    methodKind: "unary";
    input: typeof RegisterRequestSchema;
    output: typeof RegisterResponseSchema;
  },
  /**
   * @generated from rpc api.UserService.Login
   */
  login: {
    methodKind: "unary";
    input: typeof LoginRequestSchema;
    output: typeof LoginResponseSchema;
  },
  /**
   * @generated from rpc api.UserService.RefreshToken
   */
  refreshToken: {
    methodKind: "unary";
    input: typeof RefreshRequestSchema;
    output: typeof RefreshResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_user, 0);

